Run UI & API Tests 36 - add Allure Report

diff --git a/.github/workflows/RunSmokeTests.yaml b/.github/workflows/RunSmokeTests.yaml
--- a/.github/workflows/RunSmokeTests.yaml
+++ b/.github/workflows/RunSmokeTests.yaml
@@ -89,50 +89,50 @@ jobs:
           docker stop ahmad-photoprism || true
           docker rm ahmad-photoprism || true
 
-  TestAPI:
-    name: API Tests
-    runs-on: ubuntu-latest
-    needs: setup
-    steps:
-      - name: Download test repository
-        uses: actions/download-artifact@v4
-        with:
-          name: photoprism-tests
-          path: photoprism-tests
-
-      - name: Pull and Run PhotoPrism Docker Container
-        run: |
-          docker pull ahmadnas/photoprism-app
-          docker run -d --name ahmad-photoprism \
-            -v "$(pwd)/storage/originals:/photoprism/originals" \
-            -p 2342:2342 ahmadnas/photoprism-app
-
-      - name: Wait for PhotoPrism to be accessible
-        run: |
-          for i in {1..30}; do
-            curl --silent --fail http://localhost:2342 && break
-            echo "Waiting for PhotoPrism..."
-            sleep 2
-          done
-
-      - name: Launch standalone grid - Chrome (for API tests)
-        run: |
-          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:latest
-
-      - name: Run API Tests
-        run: |
-          cd photoprism-tests
-          export BROWSER=chrome
-          export GRID_URL=http://localhost:4444
-          export BASE_URL=http://localhost:2342
-          mvn clean test -Dtest=TestAutomationProjectTesting.ApiTest
-          
-      
-
-      - name: Tear down containers
-        if: always()
-        run: |
-          docker stop grid_container || true
-          docker rm grid_container || true
-          docker stop ahmad-photoprism || true
-          docker rm ahmad-photoprism || true
+#  TestAPI:
+#    name: API Tests
+#    runs-on: ubuntu-latest
+#    needs: setup
+#    steps:
+#      - name: Download test repository
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: photoprism-tests
+#          path: photoprism-tests
+#
+#      - name: Pull and Run PhotoPrism Docker Container
+#        run: |
+#          docker pull ahmadnas/photoprism-app
+#          docker run -d --name ahmad-photoprism \
+#            -v "$(pwd)/storage/originals:/photoprism/originals" \
+#            -p 2342:2342 ahmadnas/photoprism-app
+#
+#      - name: Wait for PhotoPrism to be accessible
+#        run: |
+#          for i in {1..30}; do
+#            curl --silent --fail http://localhost:2342 && break
+#            echo "Waiting for PhotoPrism..."
+#            sleep 2
+#          done
+#
+#      - name: Launch standalone grid - Chrome (for API tests)
+#        run: |
+#          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:latest
+#
+#      - name: Run API Tests
+#        run: |
+#          cd photoprism-tests
+#          export BROWSER=chrome
+#          export GRID_URL=http://localhost:4444
+#          export BASE_URL=http://localhost:2342
+#          mvn clean test -Dtest=TestAutomationProjectTesting.ApiTest
+#
+#
+#
+#      - name: Tear down containers
+#        if: always()
+#        run: |
+#          docker stop grid_container || true
+#          docker rm grid_container || true
+#          docker stop ahmad-photoprism || true
+#          docker rm ahmad-photoprism || true
